### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by nickpizzo** [jkup/mastering-chrome-devtools#2]
hello I have an app with a similar structure to this (layouts in a views folder, and the rest of the assets in a public folder). The dev server works well, but I'm not exactly sure of the proper technique to deploy this app to a live url. Are there any further resources on this you would recommend? thanks

**Comment by jkup** [comment]
Hey @nickpizzo!

Sorry I didn't get to this earlier. Deploying node apps to production is a little difficult but there are some great guides out there like https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04

Basically you need a server, (digialocean offers great ones!) and then you install nginx + node + something like https://www.npmjs.com/package/pm2 which will help manage your app in production.

Let me know if you run into any troubles!
