### ISSUE TITLE
debugging2.js not served from the debugging page

### ISSUE THREAD

**Issue by looshi** [jkup/mastering-chrome-devtools#5]
This isn't a major deal, but took me a minute to figure out.  maybe it will help others watching the debugger and breakpoints videos.

Using Chrome Version 55.0.2883.95 (64-bit)

Steps to replicate : 
```
node server.js

navigate to : http://localhost:3000/debugging

Open chrome dev tools, click sources tab.
```
Expected : 
I can see the "debugging2.js" file in my Dev Tools "Sources" tab

Actual : 
The "debugging2.js" file does not appear in the sources tab, nor does it appear in the list of files when searching with Cmd + P.

Notes : 
Editing server.js and including 'debugging2.js' serves the file and it appears in my sources tab.
```
// Debugging Demo
app.get('/debugging', function (req, res) {
  res.render('debugging', {
    scripts: ['debugging.js','debugging2.js']  <-- I can just add it here and it works.
  })
})
```

What's strange is I think after creating a Workspace and adding my local files I was able to see the debugging2.js, even after I removed the Workspace.  But then on subsequent refreshes of the page the file debugging2.js no longer appeared under the sources tab, so I went ahead and edited server.js as above.

Good class, I'm learning a lot, thanks!

Before editing server.js to serve the file explicity : 

![screen shot 2017-01-26 at 11 55 04 am](https://cloud.githubusercontent.com/assets/1656829/22347918/9b355f54-e3be-11e6-887b-41678afee012.png)

After editing server.js : 

![screen shot 2017-01-26 at 11 55 49 am](https://cloud.githubusercontent.com/assets/1656829/22347945/af7bd6e6-e3be-11e6-907b-ec54ba4e128c.png)

**Comment by looshi** [comment]
looks like it was removed here on purpose : 
https://github.com/jkup/mastering-chrome-devtools/commit/90362f6f91af40667238a01479d3172ac2861c55

Maybe I'm missing a step in my setup.

**Comment by jkup** [comment]
Updated course for the v3 version which should fix any debugging.js issues!
