### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by javier-rivera-deel** [jkup/mastering-chrome-devtools#6]
when doing `npm install` i keep getting errors about not being able to find some packages, current error points: 

```
npm ERR! code E404
npm ERR! 404 Not Found: @types/babylon@^6.16.2
```

Tried installing through yarn, but got the same error.

edit: this only happens in mac, in windows 10 i was able to run `npm install` with no issues

**Comment by Cirediallo** [comment]
this is old but if it is not solved can you share the logs.
But you can try this first:
`npm config set registry http://registry.npmjs.org`
and make sure that you are in the root directory

**Comment by jkup** [comment]
Updated the course, please let me know if you continue to have any issues!!
