### ISSUE TITLE
Shift + Click to change color format is broken

### ISSUE THREAD

**Issue by sevillaarvin** [jkup/mastering-chrome-devtools#8]
On `Fedora 30 - Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)`, when I Shift + Click the color in Styles tab, the color format changes but it reverts back when the list item with class `domChanges` has an attribute change/toggle.

https://masteringdevtools.com/lessons/editing

![Peek 2020-01-19 11-08](https://user-images.githubusercontent.com/33614172/72673985-70d4c680-3aac-11ea-895b-1124cafbaa2b.gif)

Works fine on Firefox though.

**Comment by jkup** [comment]
That's really interesting. Not a bug I can fix on my end! I'll experiment a bit more with Chrome on Linux and see if I can add a note to the course about it! Thanks.
