### ISSUE TITLE
Demo website not available

### ISSUE THREAD

**Issue by fadamakis** [jkup/mastering-chrome-devtools#9]
Seems like the demo website is no longer available in any of the following URLs
https://mastering-chrome-devtools-2.vercel.app/
https://masteringdevtools.com/

Probably related to the latest commit of 23/8
https://github.com/jkup/mastering-chrome-devtools/commit/c86135964d799a87ae858308e6eb53d5c52f82d3

**Comment by jkup** [comment]
Hey there! That commit was my attempt to get it working again but it looks like Vercel stopped support for Node/Express apps. I'm gonna migrate the demo site to a new host this weekend! Sorry for the downtime!

**Comment by charleskyalo** [comment]
> Seems like the demo website is no longer available in any of the following URLs
> https://mastering-chrome-devtools-2.vercel.app/
> https://masteringdevtools.com/
> 
> Probably related to the latest commit of 23/8
> [c861359](https://github.com/jkup/mastering-chrome-devtools/commit/c86135964d799a87ae858308e6eb53d5c52f82d3)

## Experienced the same problem too just as @fadamakis when I tried accessing the site today.

**Comment by fadamakis** [comment]
@charleskyalo Cloning the repo and serving the app locally worked for me.

**Comment by charleskyalo** [comment]
### Thank you @fadamakis  I have given it a shot and its working :smiley:

**Comment by jkup** [comment]
Awesome! Thanks all.
